### ISSUE TITLE
同时启动多个项目, 启动失败

### ISSUE THREAD

**Issue by herryup** [nacos-group/nacos-sdk-go#412]
go  v1.17.2
nacos-sdk-go v2.0.0

1. 使用goland同时启动多个项目, 经常出现多个项目无法启动.报错内容如下.
2. 若单独一个一个启动进程, 可以启动成功.

2022-02-24T15:03:40.148+0800    ERROR   cache/disk_cache.go:52  read cacheDir:..\cache\game1\naming\7683048c-3770-40f3-83d0-e4984b4fbf82 failed!err:open ..\cache\game1\naming\7683048c-3770-40f3-83d0-e4984b4fbf82: The system cannot find the file specified.
2022-02-24T15:03:40.149+0800    ERROR   naming_http/push_receiver.go:67 error listening :55045,err:listen udp :55045: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2022-02-24T15:03:40.149+0800    ERROR   naming_http/push_receiver.go:67 error listening :55045,err:listen udp :55045: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2022-02-24T15:03:40.149+0800    ERROR   naming_http/push_receiver.go:67 error listening :55045,err:listen udp :55045: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2022-02-24T15:03:40.149+0800    ERROR   naming_http/push_receiver.go:90 failed to start udp server after trying 3 times.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17b99dd]

goroutine 48 [running]:
panic({0x1cc3da0, 0x24ee190})
        D:/Venv/Go/src/runtime/panic.go:1147 +0x3a6 fp=0xc0003bdef0 sp=0xc0003bde30 pc=0xffc466
runtime.panicmem()
        D:/Venv/Go/src/runtime/panic.go:221 +0x45 fp=0xc0003bdf10 sp=0xc0003bdef0 pc=0xffa4c5
runtime.sigpanic()
        D:/Venv/Go/src/runtime/signal_windows.go:254 +0xd1 fp=0xc0003bdf40 sp=0xc0003bdf10 pc=0x1011271
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_http.(*PushReceiver).startServer.func1()
        D:/Git/NTF/server/src/vendor/github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_http/push_receiver.go:95 +0x3d fp=0xc0003bdfe0 sp=0xc0003bdf40 pc=0x17b99dd
runtime.goexit()
        D:/Venv/Go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0003bdfe8 sp=0xc0003bdfe0 pc=0x102e141
created by github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_http.(*PushReceiver).startServer
        D:/Git/NTF/server/src/vendor/github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_http/push_receiver.go:94 +0x245

**Comment by sanxun0325** [comment]
sdk启动时会开启udp端口，同时并发启动 有可能出现端口重复的情况，所以会报错`2022-02-24T15:03:40.149+0800 ERROR naming_http/push_receiver.go:67 error listening :55045,err:listen udp :55045: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.`

**Comment by herryup** [comment]
谢谢回复, 若只是报错倒也无所谓. 目前的问题是
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x17b99dd]
无法提供正确的服务.

**Comment by sanxun0325** [comment]
可以用2.0.0分之的最新代码尝试一下
